version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: backend-sqlserver
    environment:
      - SA_PASSWORD=Halil007
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  app:
    build: .
    container_name: nodeapp-hiking
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./pdfs:/app/pdfs
    depends_on:
      - db
volumes:
  sql_data:
